# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
latex: true
dist: trusty 

env:
    global:
        - MAKEFLAGS="-j 2"
 
matrix:
  include:
    - r: oldrel
    - r: release
      env: R_RELEASE=true  
    - r: devel
      env: R_DEVEL=true
script:
    - pwd
    - ls -lah
    - sh .travis_script.sh
after_success:
    - sh .travis_after_success.sh
notifications:
    email:
        on_success: change
        on_failure: change
